name=ModdifiedVigenereCipher
version=1.0.0
author=echo("637_NrF3D") <alex.goldshtaen@gmail.com>
maintainer=echo("637_NrF3D") <alex.goldshtaen@gmail.com>
sentence=Library made for MPO to encode and decode with Vigenere Cipher 
paragraph=Vigenere Cipher
category=Data Processing
url=https://github.com/agoldprogcorp/moddifiedvigenerecipher
architectures=*
